# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_pages\ogrenci_listesi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OgrenciListesiForm(object):
    def setupUi(self, OgrenciListesiForm):
        OgrenciListesiForm.setObjectName("OgrenciListesiForm")
        OgrenciListesiForm.resize(1309, 784)
        OgrenciListesiForm.setFixedSize(1309, 784)
        self.frame = QtWidgets.QFrame(OgrenciListesiForm)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1311, 771))
        self.frame.setStyleSheet("QPushButton{\n"
                                 "height:42px;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.sinif_listesi = QtWidgets.QTableWidget(self.frame)
        self.sinif_listesi.setStyleSheet("selection-background-color: rgb(233, 185, 110);")
        self.sinif_listesi.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.sinif_listesi.setObjectName("sinif_listesi")
        self.sinif_listesi.setColumnCount(10)
        self.sinif_listesi.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        self.sinif_listesi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.sinif_listesi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinif_listesi.setHorizontalHeaderItem(9, item)
        self.gridLayout.addWidget(self.sinif_listesi, 0, 0, 1, 1)

        self.retranslateUi(OgrenciListesiForm)
        QtCore.QMetaObject.connectSlotsByName(OgrenciListesiForm)

    def retranslateUi(self, OgrenciListesiForm):
        _translate = QtCore.QCoreApplication.translate
        OgrenciListesiForm.setWindowTitle(_translate("OgrenciListesiForm", "Form"))
        self.pushButton.setText(_translate("OgrenciListesiForm", "Öğrenciyi Düzenle"))
        self.sinif_listesi.setWhatsThis(
            _translate("OgrenciListesiForm", "<html><head/><body><p>Öğrencilerin Bulunduğu Liste</p></body></html>"))
        item = self.sinif_listesi.verticalHeaderItem(0)
        item.setText(_translate("OgrenciListesiForm", "1"))
        item = self.sinif_listesi.verticalHeaderItem(1)
        item.setText(_translate("OgrenciListesiForm", "2"))
        item = self.sinif_listesi.verticalHeaderItem(2)
        item.setText(_translate("OgrenciListesiForm", "3"))
        item = self.sinif_listesi.verticalHeaderItem(3)
        item.setText(_translate("OgrenciListesiForm", "4"))
        item = self.sinif_listesi.verticalHeaderItem(4)
        item.setText(_translate("OgrenciListesiForm", "5"))
        item = self.sinif_listesi.verticalHeaderItem(5)
        item.setText(_translate("OgrenciListesiForm", "6"))
        item = self.sinif_listesi.verticalHeaderItem(6)
        item.setText(_translate("OgrenciListesiForm", "7"))
        item = self.sinif_listesi.verticalHeaderItem(7)
        item.setText(_translate("OgrenciListesiForm", "8"))
        item = self.sinif_listesi.verticalHeaderItem(8)
        item.setText(_translate("OgrenciListesiForm", "10"))
        item = self.sinif_listesi.verticalHeaderItem(9)
        item.setText(_translate("OgrenciListesiForm", "11"))
        item = self.sinif_listesi.verticalHeaderItem(10)
        item.setText(_translate("OgrenciListesiForm", "12"))
        item = self.sinif_listesi.verticalHeaderItem(11)
        item.setText(_translate("OgrenciListesiForm", "13"))
        item = self.sinif_listesi.verticalHeaderItem(12)
        item.setText(_translate("OgrenciListesiForm", "14"))
        item = self.sinif_listesi.verticalHeaderItem(13)
        item.setText(_translate("OgrenciListesiForm", "16"))
        item = self.sinif_listesi.horizontalHeaderItem(0)
        item.setText(_translate("OgrenciListesiForm", "Id"))
        item = self.sinif_listesi.horizontalHeaderItem(1)
        item.setText(_translate("OgrenciListesiForm", "No"))
        item = self.sinif_listesi.horizontalHeaderItem(2)
        item.setText(_translate("OgrenciListesiForm", "Adı"))
        item = self.sinif_listesi.horizontalHeaderItem(3)
        item.setText(_translate("OgrenciListesiForm", "Soyadı"))
        item = self.sinif_listesi.horizontalHeaderItem(4)
        item.setText(_translate("OgrenciListesiForm", "Programı"))
        item = self.sinif_listesi.horizontalHeaderItem(5)
        item.setText(_translate("OgrenciListesiForm", "Sınıf"))
        item = self.sinif_listesi.horizontalHeaderItem(6)
        item.setText(_translate("OgrenciListesiForm", "Bölüm"))
        item = self.sinif_listesi.horizontalHeaderItem(7)
        item.setText(_translate("OgrenciListesiForm", "Şube"))
        item = self.sinif_listesi.horizontalHeaderItem(8)
        item.setText(_translate("OgrenciListesiForm", "Resim Yolu"))
        item = self.sinif_listesi.horizontalHeaderItem(9)
        item.setText(_translate("OgrenciListesiForm", "Alınan Dersler"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    OgrenciListesiForm = QtWidgets.QWidget()
    ui = Ui_OgrenciListesiForm()
    ui.setupUi(OgrenciListesiForm)
    OgrenciListesiForm.show()
    sys.exit(app.exec_())
